import Head from "next/head";
import React, { useState } from "react";
import { NavBar, TabBar } from "antd-mobile";
import {
  AppOutline,
  MessageOutline,
  MessageFill,
  UnorderedListOutline,
  UserOutline,
} from "antd-mobile-icons";
import styles from "@/styles/ClientLayout.module.css";
import { useRouter } from "next/router";
const ClientLayout = (props: any) => {
  const router = useRouter();
  const [navBar, setNavBar] = useState("首页");
  const tabs = [
    {
      key: "1",
      title: "信息登记",
      icon: <AppOutline />,
      link: "/client",
    },
    {
      key: "2",
      title: "住院记录",
      icon: <UnorderedListOutline />,
      link: "/client/medicalRecord",
    },
    {
      key: "3",
      title: "我的信息",
      icon: <MessageOutline />,
      link: "/client/msg",
    },
    // {
    //   key: "4",
    //   title: "消息",
    //   icon: <UserOutline />,
    //   link: "/client/patientAdd",
    // },
  ];

  const handleTabBarChange = (key: string) => {
    switch (key) {
      case "1":
        setNavBar(tabs[0].title);
        router.replace(tabs[0].link);
        break;
      case "2":
        setNavBar(tabs[1].title);
        router.replace(tabs[1].link);
        break;
      case "3":
        setNavBar(tabs[2].title);
        router.replace(tabs[2].link);
        break;

      default:
        setNavBar(tabs[3].title);
        router.replace(tabs[3].link);
        break;
    }
  };
  return (
    <>
      <Head>
        <title>Client App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.app}>
        <div className={styles.top}>
          <NavBar back={null}>{navBar}</NavBar>
        </div>
        <div className={styles.body}>{props.children}</div>
        <div className={styles.bottom}>
          <TabBar onChange={handleTabBarChange}>
            {tabs.map((item) => (
              <TabBar.Item key={item.key} icon={item.icon} title={item.title} />
            ))}
          </TabBar>
        </div>
      </div>
    </>
  );
};

export default ClientLayout;
