import Head from "next/head";
import React, { useEffect, useState } from "react";
import {
  Button,
  DatePicker,
  Form,
  Select,
  Space,
  Switch,
  Table,
  message,
  theme,
} from "antd";
import type { ColumnsType, TablePaginationConfig } from "antd/es/table";
import type {
  FilterValue,
  SorterResult,
  TableRowSelection,
} from "antd/es/table/interface";
import { useQuery, useQueryClient } from "react-query";
import axios from "axios";
import { drugType, mrType } from "./dataType";
import dayjs from "dayjs";

const dName = ["内科", "外科", "妇产科", "小儿科", "神经科", "消化内科", "All"];

export default function FinancialChartPage() {
  const [form] = Form.useForm();
  const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([]);
  const [dataSource, setDataSource] = useState<mrType[]>();

  return (
    <>
      <Head>
        <title>财务报表</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
