import Head from "next/head";
import dynamic from "next/dynamic";
const QueryMoneyTable = dynamic(
  () => import("@/components/form/queryMoneyTable"),
  {
    ssr: false,
  }
); // Async API cannot be server-side rendered

export default function FinancialTablePage() {
  return (
    <>
      <Head>
        <title>财务账单</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryMoneyTable></QueryMoneyTable>
    </>
  );
}
