import Welcome from "@/components/welcome/welcome";
import Head from "next/head";
import type { ReactElement } from "react";
import type { NextPageWithLayout } from "./_app";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>HHS SYSTEM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome />
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  // page属性就是当前页面组件component的内容
  // 有需要的话可以在此基础上多嵌套几个layout组件
  return page;
};

export default Home;
