import Head from "next/head";
import dynamic from "next/dynamic";

const AuthForm = dynamic(import("@/components/auth/auth-form"), { ssr: false }); // Async API cannot be server-side rendered
export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthForm />
    </>
  );
}
